name: Add comment
on:
  issues:
    types:
      - labeled
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
jobs:
  run-initial-benchmark:
    if: github.event.label.name == 'perf'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write
      actions: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x' # Ensure this matches the TargetFramework in your .csproj file

      - name: Restore dependencies
        run: dotnet restore
      - name: Run Benchmarks
        run: dotnet run -c Release --project tests/Benchmarks/Benchmarks.csproj
      - name: Upload baseline benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: baseline-results
          path: artifacts/results/

  run-perf-fix-benchmark:
    if: github.event.label.name == 'perf'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write
      actions: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        # Check out from the branch that contains the fix - this will be a SHA or a branch name we get from the fix generation step.
        ref: 'dev/jabovee/stringutils-fix'

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x' # Ensure this matches the TargetFramework in your .csproj file

      - name: Restore dependencies
        run: dotnet restore
      - name: Run Benchmarks
        run: dotnet run -c Release --project tests/Benchmarks/Benchmarks.csproj
      - name: Upload baseline benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: fix-results
          path: artifacts/results/
  